### ISSUE TITLE
Trying to get single item from collection via  URL results in 404

### ISSUE THREAD

**Issue by HarmdR** [pcraster/gghdc#120]
-gghdc/properties/1 - The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

-gghdc/aggregate_queries/1 - The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

-/gghdc/tasks/1 - The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by kordejong** [comment]
Should work now. Tasks are an implementation detail, so you can't get individual ones. You shouldn't use /emis/tasks. It's there for the EMIS dashboard only.
